name: iOS Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test
        run: xcodebuild test -testPlan "Fuel Logue" -destination 'platform=iOS Simulator,name=iPhone 11'
